/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.ModeloTabela;
import ModelBeans.ProdutoBeans;
import ModelConexao.ConexaoBD;
import ModelDao.ProdutoDao;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Junior Macie
 */
public class StockMDI extends javax.swing.JInternalFrame {
    
    ProdutoBeans mod = new ProdutoBeans();
    ConexaoBD conex = new ConexaoBD();
    ModelDao.ProdutoDao control = new ProdutoDao();
    ProdutoDao dao = new ProdutoDao();
    /**
     * Creates new form StockMDI
     */
    public StockMDI() {
        initComponents();
        preencherTabela("select * from produto order by id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jTextFieldAdicionar = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNomeDoMaterial = new javax.swing.JTextField();
        jTextFieldValorPorUnidade = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonPesquisar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterial = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulário Para Estoque De Produto");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/Logo manengo cortada2.png"))); // NOI18N

        jTextFieldPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPesquisar.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Adicionar");
        jButton4.setToolTipText("Adicionar Nova Quantidade");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextFieldAdicionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdicionarActionPerformed(evt);
            }
        });

        jTextFieldQuantidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldQuantidade.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Qtd Adicionar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Qtd Atual");

        jTextFieldNomeDoMaterial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldNomeDoMaterial.setEnabled(false);
        jTextFieldNomeDoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeDoMaterialActionPerformed(evt);
            }
        });

        jTextFieldValorPorUnidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldValorPorUnidade.setEnabled(false);

        jTextFieldId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldId.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Codigo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Nome do material");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Valor Por Unidade");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeDoMaterial, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldValorPorUnidade)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addComponent(jTextFieldQuantidade)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAdicionar)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeDoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorPorUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonPesquisar1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPesquisar1.setText("Pesquisar");
        jButtonPesquisar1.setToolTipText("Efectuar Pesquisa Pelo Nome");
        jButtonPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisar1ActionPerformed(evt);
            }
        });

        jTableMaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMaterial);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1131, 782);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int novaQuantidade;
        int actualQuantidade;
        int adicionar;

        actualQuantidade = Integer.parseInt(jTextFieldQuantidade.getText());
        adicionar        = Integer.parseInt(jTextFieldAdicionar.getText());
        novaQuantidade   = adicionar + actualQuantidade;

        int codigo = Integer.parseInt(jTextFieldId.getText());
        dao.aumentar(novaQuantidade, codigo);
        preencherTabela("select * from produto order by id");
        jTextFieldAdicionar.setText("");
        jTextFieldId.setText("");
        jTextFieldNomeDoMaterial.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldValorPorUnidade.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdicionarActionPerformed

    private void jTextFieldNomeDoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeDoMaterialActionPerformed

    }//GEN-LAST:event_jTextFieldNomeDoMaterialActionPerformed

    private void jTableMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMaterialMouseClicked

        String nome = ""+jTableMaterial.getValueAt(jTableMaterial.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from produto where nome='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldId.setText(String.valueOf(conex.rs.getInt("id")));
            jTextFieldNomeDoMaterial.setText(String.valueOf(conex.rs.getString("nome")));
            jTextFieldQuantidade.setText(String.valueOf(conex.rs.getInt("qtd")));
            jTextFieldValorPorUnidade.setText(String.valueOf(conex.rs.getFloat("valor")));

            jTextFieldNomeDoMaterial.setEnabled(false);
            jTextFieldQuantidade.setEnabled(false);
            jTextFieldValorPorUnidade.setEnabled(false);

            preencherTabela("select * from produto order by id");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO SELECIONAR" +ex);
        }
        conex.desconexao();
    }//GEN-LAST:event_jTableMaterialMouseClicked

    public void preencherTabela(String sql){
            
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Nome","Quantidade","Valor Por Unidade"};
        conex.conexao();
        
        conex.executaSql(sql);
            try {
                conex.rs.first();
                do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("nome"),conex.rs.getInt("qtd"),conex.rs.getFloat("valor")});  
                }while(conex.rs.next());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERRO AO PREENCHER ARRAYLIST"+ex);
            }
            
            ModeloTabela modelo = new ModeloTabela(dados, colunas);
            
            jTableMaterial.setModel(modelo);
            jTableMaterial.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableMaterial.getColumnModel().getColumn(0).setResizable(false);
            jTableMaterial.getColumnModel().getColumn(1).setPreferredWidth(225);
            jTableMaterial.getColumnModel().getColumn(1).setResizable(false);
            jTableMaterial.getColumnModel().getColumn(2).setPreferredWidth(160);
            jTableMaterial.getColumnModel().getColumn(2).setResizable(false);
            jTableMaterial.getColumnModel().getColumn(3).setPreferredWidth(160);
            jTableMaterial.getColumnModel().getColumn(3).setResizable(false);
            jTableMaterial.getTableHeader().setReorderingAllowed(false);
            jTableMaterial.setAutoResizeMode(jTableMaterial.AUTO_RESIZE_ALL_COLUMNS);
            jTableMaterial.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            conex.desconexao();
        }
    
    private void jButtonPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisar1ActionPerformed

        mod.setPesquisa(jTextFieldPesquisar.getText());
        ProdutoBeans model = control.buscaProduto(mod);

        jTextFieldId.setText(String.valueOf(model.getId()));
        jTextFieldNomeDoMaterial.setText(model.getNmproduto());
        jTextFieldQuantidade.setText(String.valueOf(model.getQtd()));
        jTextFieldValorPorUnidade.setText(String.valueOf(model.getValor()));

        jTextFieldId.setEnabled(false);
        jTextFieldNomeDoMaterial.setEnabled(false);
        jTextFieldQuantidade.setEnabled(false);
        jTextFieldValorPorUnidade.setEnabled(false);

        jTextFieldId.setText("");
        jTextFieldNomeDoMaterial.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldValorPorUnidade.setText("");

        preencherTabela("select * from produto where nome like '%" + mod.getPesquisa() + "%'");
    }//GEN-LAST:event_jButtonPesquisar1ActionPerformed
    
    
    
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonPesquisar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMaterial;
    private javax.swing.JTextField jTextFieldAdicionar;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNomeDoMaterial;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldValorPorUnidade;
    // End of variables declaration//GEN-END:variables
}
