/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.Hora;
import ModelBeans.ModeloTabela;
import ModelBeans.ProdutoBeans;
import ModelBeans.UsuarioBeans;
import ModelBeans.VendaBeans;
import ModelConexao.ConexaoBD;
import ModelDao.ProdutoDao;
import ModelDao.UsuarioDao;
import ModelDao.VendaDao;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Junior Macie
 */
public class VendaMDI extends javax.swing.JInternalFrame {

    ProdutoBeans mode = new ProdutoBeans();
    ModelDao.ProdutoDao controle = new ProdutoDao();
    ProdutoDao dau = new ProdutoDao();
    UsuarioBeans modes = new UsuarioBeans();
    ModelDao.UsuarioDao controler = new UsuarioDao();
    UsuarioDao daos = new UsuarioDao();
    ConexaoBD conex = new ConexaoBD();
    
    int flag = 0;
    
    VendaBeans mod = new VendaBeans();
    ModelDao.VendaDao control = new VendaDao();
    VendaDao dao = new VendaDao();
    /**
     * Creates new form VendaMDI
     */
    public VendaMDI() {
        initComponents();
//        conex.conexao();
//        preencherProduto();
//        preencherTabela("select * from venda order by cliente");
//        preencherFuncionario();
        //timer1.start();
        
        //Serve Para Exibir A Data Actual Do Sistema.
        Date data = new Date();
        DateFormat formatadorD = DateFormat.getDateInstance(DateFormat.LONG);
        jLabelData.setText(formatadorD.format(data));
        
        //Agora A Hora Do Sistema    
        Hora mostra_hora = new Hora();
        mostra_hora.ler_hora();
        jLabelHora.setText(mostra_hora.hora);        
        
    }
    
    public void preencherFuncionario(){
        conex.conexao();
        conex.executaSql("select * from usuario order by nome");
        try {
            conex.rs.first();
            jComboBoxFuncionario.removeAllItems();
            do{
                jComboBoxFuncionario.addItem(conex.rs.getString("nome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro Ao Preencher ComboBox");
        }
        conex.desconexao();
    }
    
    public void preencherProduto(){
        conex.conexao();
        conex.executaSql("select * from produto order by nome");
        try {
            conex.rs.first();
            jComboBoxProduto.removeAllItems();
            do{
                jComboBoxProduto.addItem(conex.rs.getString("nome"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro Ao Preencher ComboBox");
        }
        conex.desconexao();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldContacto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldIdMateriald = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldQtdAtual = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldQtdDesejada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldValorPagar = new javax.swing.JTextField();
        jTextFieldPagamento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jButtonVender = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonNova = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/image/Logo manengo cortada2.png"))); // NOI18N

        jTextFieldPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPesquisar.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jTextFieldId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldId.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Codigo De Venda");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nome De Usuario");

        jComboBoxFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nome Do Cliente");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Contacto Do Cliente");

        jTextFieldContacto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Endereco Do Cliente");

        jTextFieldEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Produto Desejado");

        jTextFieldIdMateriald.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldIdMateriald.setText("Codigo De Produto");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Qtd Disponivel");

        jTextFieldQtdAtual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldQtdAtual.setEnabled(false);

        jTextFieldPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPreco.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Preco Unitario");

        jTextFieldQtdDesejada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldQtdDesejada.setMinimumSize(null);
        jTextFieldQtdDesejada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQtdDesejadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQtdDesejadaKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Qtd Desejada");
        jLabel7.setMinimumSize(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Valor A Pagar");

        jTextFieldValorPagar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldValorPagar.setEnabled(false);

        jTextFieldPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Pagamento");

        jComboBoxProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextFieldPagamento, org.jdesktop.beansbinding.ObjectProperty.create(), jComboBoxProduto, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProdutoItemStateChanged(evt);
            }
        });
        jComboBoxProduto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jComboBoxProdutoMouseDragged(evt);
            }
        });
        jComboBoxProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxProdutoPopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBoxProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxProdutoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxProdutoMousePressed(evt);
            }
        });

        jButtonVender.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonVender.setText("Vender");
        jButtonVender.setToolTipText("Salvar");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVenderActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonNova.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonNova.setText("Nova Venda");
        jButtonNova.setToolTipText("Cancelar");
        jButtonNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldEndereco)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldContacto)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCliente)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(8, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdDesejada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonNova, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 19, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldIdMateriald, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldQtdAtual)
                                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPagamento)
                                    .addComponent(jTextFieldValorPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQtdDesejada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldQtdAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdMateriald, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNova, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVendasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableVendas);

        jButtonPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setToolTipText("Efectuar Pesquisa Pelo Nome");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Data:");

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Hora:");

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        setBounds(0, 0, 1131, 782);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldQtdDesejadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdDesejadaKeyReleased

        float preco;
        int quantidadeDesejada = Integer.parseInt(jTextFieldQtdDesejada.getText());
        preco = Float.parseFloat(jTextFieldPreco.getText());
        float valorAPagar = (quantidadeDesejada * preco);

        jTextFieldValorPagar.setText("" +valorAPagar);
    }//GEN-LAST:event_jTextFieldQtdDesejadaKeyReleased

    private void jTextFieldQtdDesejadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdDesejadaKeyPressed

    }//GEN-LAST:event_jTextFieldQtdDesejadaKeyPressed

    private void jTableVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVendasMouseClicked

        String nome = ""+jTableVendas.getValueAt(jTableVendas.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from venda where usuario='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldId.setText(String.valueOf(conex.rs.getInt("id")));
            jTextFieldCliente.setText(conex.rs.getString("cliente"));
            jTextFieldContacto.setText(conex.rs.getString("contacto"));
            jTextFieldEndereco.setText(conex.rs.getString("endereco"));
//            jTextFieldEstado.setText(conex.rs.getString("estado"));
            jTextFieldPagamento.setText(conex.rs.getString("pagamento"));
            jTextFieldPreco.setText(conex.rs.getString("precoun"));
            jTextFieldQtdDesejada.setText(conex.rs.getString("qtd"));
            jTextFieldValorPagar.setText(conex.rs.getString("vapagar"));
            jComboBoxFuncionario.setSelectedItem(String.valueOf(conex.rs.getString("usuario")));

            //                mod.setUsuario((String)jComboBoxFuncionario.getSelectedItem());
            //                mod.setCliente(jTextFieldCliente.getText());
            //                mod.setContacto(jTextFieldCliente.getText());
            //                mod.setEndereco(jTextFieldEndereco.getText());
            //                mod.setProduto((String)jTableMaterial.getValueAt(jTableMaterial.getSelectedRow(), 0));;
            //                mod.setQtd(Integer.valueOf(jTextFieldQtdDesejada.getText()));
            //                mod.setPrecoun(Float.valueOf(jTextFieldPreco.getText()));
            //                mod.setVapagar(Float.valueOf(jTextFieldValorPagar.getText()));
            //                mod.setPagamento(Float.valueOf(jTextFieldPagamento.getText()));
            //                mod.setData(jLabelData.getText());
            //                mod.setHora(jLabelHora.getText());
            //                mod.setEstado(jTextFieldEstado.getText());

            //                    jButtonVender.setEnabled(true);
            //
            //                    int resposta = 0;
            //                    resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Vender?");
            //                    if(resposta == JOptionPane.YES_NO_OPTION){
                //                        JOptionPane.showMessageDialog(rootPane, "Venda Realizada Com Sucesso! Agora Confirme A Venda");
                //                    }
            //
            //                    jTextFieldEstado.setText("Venda Realizada");

            //                control.vender(mod);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO AO SELECIONAR " +ex);
        }
        conex.desconexao();
    }//GEN-LAST:event_jTableVendasMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        //        mod.setPesquisa(jTextFieldPesquisar.getText());
        //        FuncionarioBeans model = control.buscaFuncionario(mod);
        //        VendaBeans model = control.buscarVenda(mod);
        //        jTextFieldFaltas.setText(String.valueOf(model.getCodigo()));
        //        jTextFieldNascimentoFuncionario.setText(String.valueOf(model.getNascimento()));
        //        jTextFieldNomeFuncionario.setText(model.getNome());
        //        jTextFieldCliente.setText(model.getContacto());
        //        jComboBoxEstadoCivilFuncionario.setSelectedItem(model.getEstadoCivil());
        //        jComboBoxSexoFuncionario.setSelectedItem(model.getSexo());
        //        jTextFieldContacto.setText(model.getNrDeIdentificacao());
        //
        //        jButtonEditar.setEnabled(true);
        //        jButtonExcluir.setEnabled(true);
        //        jButtonSalvar.setEnabled(false);
        //
        //        jTextFieldFaltas.setEnabled(false);
        //        jTextFieldNascimentoFuncionario.setEnabled(false);
        //        jTextFieldNomeFuncionario.setEnabled(false);
        //        jTextFieldCliente.setEnabled(false);
        //        jComboBoxEstadoCivilFuncionario.setEnabled(false);
        //        jComboBoxSexoFuncionario.setEnabled(false);
        //        jTextFieldContacto.setEnabled(false);
        //
        //        jTextFieldFaltas.setText("");
        //        jTextFieldNascimentoFuncionario.setText("");
        //        jTextFieldNomeFuncionario.setText("");
        //        jTextFieldCliente.setText("");
        //        jTextFieldContacto.setText("");
        //
        //        preencherTabela("select * from fornecedor where nomeempresa like '%" + mod.getPesquisa() + "%'");
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jComboBoxProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxProdutoMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoMouseClicked

    private void jButtonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVenderActionPerformed

      jTextFieldPesquisar.setText("");
            int novaQuantidade;
            int actualQuantidade;
            int remover;

            actualQuantidade = Integer.parseInt(jTextFieldQtdAtual.getText());
            remover        = Integer.parseInt(jTextFieldQtdDesejada.getText());
            novaQuantidade   = (actualQuantidade - remover);

            int codigo = Integer.parseInt(jTextFieldIdMateriald.getText());
            dau.remocao(novaQuantidade, codigo);
            
        if (jTextFieldCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha O Campo 'Nome Do Cliente' Para Continuar!");
            jTextFieldCliente.requestFocus();
        }else if(jTextFieldContacto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha O Campo 'Contacto Do Cliente' Para Continuar!");
            jTextFieldContacto.requestFocus();
        }else if(jTextFieldEndereco.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha O Campo 'Endereco Do Cliente' Para Continuar!");
            jTextFieldEndereco.requestFocus();
        } else if(jTextFieldQtdDesejada.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha O Campo 'Quantidade Desejada' Para Continuar!");
            jTextFieldQtdDesejada.requestFocus();
        } else if(jTextFieldPagamento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha O Campo 'Pagamento' Para Continuar!");
            jTextFieldPagamento.requestFocus();
            } else {
            


            mod.setUsuario((String)jComboBoxFuncionario.getSelectedItem());
            mod.setCliente(jTextFieldCliente.getText());
            mod.setContacto(jTextFieldCliente.getText());
            mod.setEndereco(jTextFieldEndereco.getText());
            mod.setProduto((String)jComboBoxProduto.getSelectedItem());
            mod.setQtd(Integer.valueOf(jTextFieldQtdDesejada.getText()));
            mod.setPrecoun(Float.valueOf(jTextFieldPreco.getText()));
            mod.setVapagar(Float.valueOf(jTextFieldValorPagar.getText()));
            mod.setPagamento(Float.valueOf(jTextFieldPagamento.getText()));
            mod.setData(jLabelData.getText());
            mod.setHora(jLabelHora.getText());
            control.vender(mod);
            preencherTabela("select * from venda order by cliente");
                        
        
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonVender.setEnabled(false);
            
            jTextFieldValorPagar.setText("");
            jTextFieldQtdDesejada.setText("");
            jTextFieldQtdAtual.setText("");
            jTextFieldPreco.setText("");
            jTextFieldPagamento.setText("");
            jTextFieldIdMateriald.setText("");
            jTextFieldId.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldContacto.setText("");
            jTextFieldCliente.setText("");

            }
            
    }//GEN-LAST:event_jButtonVenderActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        //        int resposta = 0;
        //        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
        //        if(resposta == JOptionPane.YES_OPTION){
            //            mod.setCodigo(Integer.parseInt(jTextFieldFaltas.getText()));
            //            control.excluir(mod);
            //
            //            jTextFieldPesquisar.setText("");
            //            jTextFieldNomeFuncionario.setText("");
            //            jTextFieldCliente.setText("");
            //            jTextFieldNascimentoFuncionario.setText("");
            //            jTextFieldContacto.setText("");
            //            jTextFieldFaltas.setText("");
            //            jButtonEditar.setEnabled(false);
            //            jButtonExcluir.setEnabled(false);
            //
            //            preencherTabela("select * from funcionario order by id");
            //        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        //        flag = 2;
        //
        //        jButtonExcluir.setEnabled(false);
        //        jButtonSalvar.setEnabled(true);
        //        jButtonCancelar.setEnabled(true);
        //        jButtonEditar.setEnabled(false);
        //        jButtonRemover.setEnabled(false);
        //
        //        jComboBoxEstadoCivilFuncionario.setEnabled(true);
        //        jComboBoxSexoFuncionario.setEnabled(true);
        //        jTextFieldCliente.setEnabled(true);
        //        jTextFieldNascimentoFuncionario.setEnabled(true);
        //        jTextFieldNomeFuncionario.setEnabled(true);
        //        jTextFieldContacto.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaActionPerformed
        
        jButtonVender.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovaActionPerformed

    private void jComboBoxProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProdutoItemStateChanged

       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoItemStateChanged

    private void jComboBoxProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxProdutoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoMousePressed

    private void jComboBoxProdutoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxProdutoMouseDragged
   // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoMouseDragged

    private void jComboBoxProdutoPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxProdutoPopupMenuWillBecomeVisible
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoPopupMenuWillBecomeVisible

    private void jComboBoxProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxProdutoPopupMenuWillBecomeInvisible
        String nome = (String) jComboBoxProduto.getSelectedItem();
        conex.conexao();
        conex.executaSql("select * from produto where nome='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldIdMateriald.setText(String.valueOf(conex.rs.getInt("id")));
            jTextFieldQtdAtual.setText(String.valueOf(conex.rs.getInt("qtd")));
            jTextFieldPreco.setText(String.valueOf(conex.rs.getFloat("valor")));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO SELECIONAR  " +ex);
        }
        conex.desconexao();         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoPopupMenuWillBecomeInvisible

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
    String nome = ""+jTableVendas.getValueAt(jTableVendas.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("select * from venda where usuario='"+nome+"'");
        try {
            conex.rs.first();
            jTextFieldId.setText(String.valueOf(conex.rs.getInt("id")));
            jComboBoxFuncionario.setSelectedItem(String.valueOf(conex.rs.getString("usuario")));
            jTextFieldCliente.setText(String.valueOf(conex.rs.getString("cliente")));
            jTextFieldContacto.setText(String.valueOf(conex.rs.getString("contacto")));
            jTextFieldEndereco.setText(String.valueOf(conex.rs.getString("endereco")));
            jTextFieldIdMateriald.setText(String.valueOf(conex.rs.getInt("material")));
            jTextFieldPagamento.setText(String.valueOf(conex.rs.getFloat("pagamento")));
            jComboBoxProduto.setSelectedItem(String.valueOf(conex.rs.getString("")));
            jTextFieldQtdDesejada.setText(String.valueOf(conex.rs.getInt("qtd")));
            jTextFieldValorPagar.setText(String.valueOf(conex.rs.getFloat("vapagar")));

            jButtonExcluir.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
//            jButtonNovo.setEnabled(true);
//            jButtonSalvar.setEnabled(false);
//
//            jTextFieldNome.setEnabled(false);
//            jTextFieldQuantidade.setEnabled(false);
//            jFormattedTextField1.setEnabled(false);

            preencherTabela("select * from produto order by id");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO AO SELECIONAR" +ex);
        }
        conex.desconexao();        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    public void preencherTabela(String sql){
            
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Usuario","Cliente","Contacto","Endereco","Produto","QTD","PrecoUn","V A Pagar","Pagamento","Data","Hora"};
        conex.conexao();
        
        conex.executaSql(sql);
            try {
                conex.rs.first();
                do{
                  dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getString("usuario"),conex.rs.getString("cliente"),conex.rs.getString("contacto"),conex.rs.getString("endereco"),conex.rs.getString("produto"),conex.rs.getInt("qtd"),conex.rs.getFloat("precoun"),conex.rs.getFloat("vapagar"),conex.rs.getFloat("pagamento"),conex.rs.getString("data"),conex.rs.getString("hora")});  
                }while(conex.rs.next());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERRO AO PREENCHER ARRAYLIST  "+ex);
            }
            
            ModeloTabela modelo = new ModeloTabela(dados, colunas);
            
            jTableVendas.setModel(modelo);
            jTableVendas.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableVendas.getColumnModel().getColumn(0).setResizable(false);
            jTableVendas.getColumnModel().getColumn(1).setPreferredWidth(225);
            jTableVendas.getColumnModel().getColumn(1).setResizable(false);
            jTableVendas.getColumnModel().getColumn(2).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(2).setResizable(false);
            jTableVendas.getColumnModel().getColumn(3).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(3).setResizable(false);
            jTableVendas.getColumnModel().getColumn(4).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(4).setResizable(false);
            jTableVendas.getColumnModel().getColumn(5).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(5).setResizable(false);
            jTableVendas.getColumnModel().getColumn(6).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(6).setResizable(false);
            jTableVendas.getColumnModel().getColumn(7).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(7).setResizable(false);
            jTableVendas.getColumnModel().getColumn(8).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(8).setResizable(false);
            jTableVendas.getColumnModel().getColumn(9).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(9).setResizable(false);
            jTableVendas.getColumnModel().getColumn(10).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(10).setResizable(false);
            jTableVendas.getColumnModel().getColumn(11).setPreferredWidth(160);
            jTableVendas.getColumnModel().getColumn(11).setResizable(false);
            jTableVendas.getTableHeader().setReorderingAllowed(false);
            jTableVendas.setAutoResizeMode(jTableVendas.AUTO_RESIZE_ALL_COLUMNS);
            jTableVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            conex.desconexao();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNova;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JComboBox<String> jComboBoxFuncionario;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableVendas;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldContacto;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JLabel jTextFieldIdMateriald;
    private javax.swing.JTextField jTextFieldPagamento;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQtdAtual;
    private javax.swing.JTextField jTextFieldQtdDesejada;
    private javax.swing.JTextField jTextFieldValorPagar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
